<?php
/**
 * Agreement template
 */
$agreement = $this->getAgreement();
?>
<div class="field privacy-container required">
    <label for="<?php echo $block->getNameInLayout(); ?>" class="label">
        <span><?php echo $agreement->getIsHtml() ? $agreement->getCheckboxText() : $block->escapeHtml($agreement->getCheckboxText()) ?></span>
    </label>
    <div class="control">
        <input type="checkbox"
               id="<?php echo $block->getNameInLayout(); ?>"
               name="<?php echo $block->getNameInLayout(); ?>"
               value="1"
               title="<?php echo $block->escapeHtml($agreement->getCheckboxText()) ?>"
               class="checkbox"
               data-validate="{required:true}"/>
    </div>
</div>
<?php if ($block->getPageUrl() !== false) : ?>
    <div>
        <a href="<?php /* @escapeNotVerified */
        echo $block->getPageUrl() ?>" class="clearer" target="_blank"><?php /* @escapeNotVerified */
            echo __('Privacy Policy') ?></a>
    </div>
<?php endif; ?>

